---

- hosts: all
  become: true
  tasks: 


  - name: install apache2 & add php support for apache
    package:
       name: 
         - httpd
         - php
         - php-cli
         - php-common
       state: present
       update_cache: yes
