---

- hosts: all
  become: true
  tasks: 
        - name: update repo cache(CentOS)
          tags: always
          package:
                update_cache: yes
          changed_when: false
          when: ansible_distribution == "CentOS"

        - name: install apache2 & add php support for apache
          tags: always,apache,apache2,httpd
          package:
                name: 
                 - httpd
                 - php
                 - php-cli
                 - php-common
                state: present
                update_cache: yes
       

- hosts: all
  become: true
  tasks:


          - name: add ssh key for neo
            tags: always 
            authorized_key:
                    user: neo
                    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII4hIr8gQkYL52dY6F+2IkcPBe6v/AxsjPiNyXH+cHK4 ansible"


- hosts: workstation
  become: true
  tasks:
        - name: install unzip
          package:
               name: unzip

        - name: install terraform
          unarchive:
                  src: https://releases.hashicorp.com/terraform/1.10.3/terraform_1.10.3_linux_arm64.zip
                  dest: /usr/local/bin
                  remote_src: yes
                  mode: 0755
                  owner: root
                  group: root


- hosts: web_servers 
  become: true
  tasks:
          - name: install mariadb package
            tags: mariadb,centos,db
            package: 
                name: mariadb
                state: latest
            when: ansible_distribution == "CentOS"

          - name: copy html file for site
            tags: html,copy,httpd
            copy:
                src: default_site.html
                dest: /var/www/html/index.html
                owner: root
                group: root
                mode: 0644

          - name: start httpd (CentOS)
            tags: apache,centos,httpd
            service:
                   name: httpd
                   state: started
                   enabled: yes
            when: ansible_distribution == "CentOS"


- hosts: file_server
  become: true
  tasks:
          - name: install samba package
            tags: samba
            package:
                name: samba
                state: latest
            when: ansible_distribution == "CentOS"
