---

- hosts: all
  become: true
  pre_tasks: 
        - name: update repo cache(CentOS)
          tags: always
          package:
                update_cache: yes
          changed_when: false
          when: ansible_distribution == "CentOS"

        - name: install apache2 & add php support for apache
          tags: always,apache,apache2,httpd
          package:
                name: 
                 - httpd
                 - php
                 - php-cli
                 - php-common
                state: present
                update_cache: yes
       


- hosts: all
  become: true
  roles:
     - base
    
- hosts: workstation
  become: true
  roles:
     - workstation
 
- hosts: web_servers
  become: true
  roles:
     - web_servers
 
- hosts: file_server
  become: true
  roles:
     - file_server
